### ISSUE TITLE
mix array and minimatch

### ISSUE THREAD

**Issue by oupala** [aymericbeaumet/metalsmith-concat#9] opened 2015-07-30 13:36 UTC
I agree that #1 can solve some problems when * files order might matter*, we can then hard-code an array to specify the concatenation order.

But my case is slightly different, and #1 and #2 do not fit in my case. I'm using many js library. I'm using Bootstrap, I'm then also using JQuery.

I need to concat JQuery before Boostrap (which is made of many many small files) and then concat all my other files. I don't want to hard-code all my js files (I have more than 20 files, and these files may vary).

I want to be able to mix array and minimatch to get a power configuration, such as this one :

```
.use(concat({ // concat javascript
    files: ['js/jquery-2.1.1.min.js', 'js/bootstrap/*.js', 'js/**/*.js'],
    output: 'js/app.js'
}))
```

This way, I'm sure to concat JQuery in first, then all Bootstrap js, then my custom js.

Obviously, files which were already concatenated before sould not be concatenated again with following expressions (ie. JQuery and Bootstrap js should not be concatenated again by `'js/**/*.js'`).

This would make **metalsmith-concat** realy more powerful than it is today.

We could then build concatenated js from scratch and then being able to customize Boostrap easily !

**Comment by aymericbeaumet** [comment] 2015-08-03 01:01
Hey @oupala, I made the necessary. You should now be able to specify minimatch patterns via the array syntax. Same as the other issue, give it a try [here](https://github.com/aymericbeaumet/metalsmith-concat/tree/refactoring).

**Comment by oupala** [comment] 2015-08-17 15:14
As far as I tested the *refactoring* branch, it works perfectly.

Thanks for this improvement !

I let you close the issue once the new version is released.

**Comment by oupala** [comment] 2015-08-20 14:29
I see that you have closed the issue while the **refactoring* branch has not been published as an npm package.

Can you tell me when do you plan to release it ?

**Comment by aymericbeaumet** [comment] 2015-08-20 15:20
The issue is not closed yet, will do when the branch is merged/published. No ETA sorry.

**Comment by aymericbeaumet** [comment] 2015-08-25 21:30
Landed on npm

**Closed by aymericbeaumet** 2015-08-25 21:30 UTC
